//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TextEd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEXTED_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDC_EDIT_TEXT                   1000
#define IDC_TAB                         1001
#define IDC_APPLY                       1002
#define IDC_TEXTLIST                    1003
#define IDC_TEXT_CURPOS                 1004
#define IDC_TEXT_CURADDRESS             1005
#define IDC_ERROR                       1007
#define IDC_ERRORT                      1008
#define ID_FILE_OPENROM                 32771
#define ID_FILE_CLOSEROM                32772
#define ID_FILE_EXIT                    32773
#define ID_EDIT_SEARCH                  32778
#define ID_TOOLS_EXPANDROM              32779
#define ID_TOOLS_TPTEDITOR              32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
